global:
  message: Welcome to customer service prod environment!!
server:
  port: 8082
message: Hello from Prod!
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_prod
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
